
title: Family Justice Courts Practice Directions 
remote_theme: opengovsg/opendoc-theme
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: fjc-pd
  doctype: bare
kramdown:
  auto_id_stripping: true
environment: DEV
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://opendoc.sg
styling_options:
  base_color: #bc6d75
  logo_path: /assets/logo.png
