
title: Family Justice Courts Practice Directions 
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: templateindex
  doctype: bare
environment: DEV
server_LOCAL: https://opendoc.sg
server_DEV: https://opendoc.sg
